# Generated by Django 5.0.6 on 2024-05-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_employee_emp_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_start_date',
            field=models.DateField(),
        ),
    ]
